GET http://localhost:3000/players/
###

POST http://localhost:3000/players/
Content-Type : application/json

{
    "playerName":"Vishal",
    "jerseryNumber":17,
    "role":"Bowler"
}

###

GET http://localhost:3000/players/17/
###

PUT http://localhost:3000/players/2/
Content-Type:application/json

{
    "playerName":"Maneesh",
    "jerseryNumber":57,
    "role":"All-rounder"
}

###
DELETE http://localhost:3000/players/2/